name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Derive version
        id: deriveVersion
        run: |
          export MVN_VER=`sed -n 's/\s\+<version>\([0-9\.]\+\)<.*/\1/p' pom.xml|head -1`
          export TIMESTAMP=`TZ=Asia/Singapore date +'%m%d-%H%M'`
          echo "TAG_VERSION=$MVN_VER-$TIMESTAMP" >> $GITHUB_ENV
      - run: mvn clean compile package
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DEV_DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.DEV_DOCKER_AUTH }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ secrets.DEV_DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.TAG_VERSION }}
