name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        cache: maven

    - run: mvn package

    - uses: actions/cache/save@v3
      with:
        key: ${{ github.sha }}
        path: target

  release-to-uat:
    needs: build
    runs-on: ubuntu-latest
    environment: 'UAT'
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      repo: ${{ env.repo }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache/restore@v3
      id: cache
      with:
        key: ${{ github.sha }}
        path: target

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - run: echo repo=$(echo "${{github.repository}}" | tr 'A-Z' 'a-z') >>${GITHUB_ENV}

    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.repo }}:${{ steps.tag.outputs.new_tag }}

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.UAT_GKE_AUTH }}

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.UAT_GKE_CLUSTER }}
        location: ${{ secrets.UAT_GKE_ZONE }}

    - env:
        DEPLOYMENT: ${{ vars.DEPLOYMENT }}
        TAG: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.new_tag }}
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${TAG}
        kubectl rollout status deployment/${DEPLOYMENT}

  release-to-prod:
    needs: release-to-uat
    runs-on: ubuntu-latest
    environment: 'PROD'
    steps:
    - uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.PROD_GKE_AUTH }}

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.PROD_GKE_CLUSTER }}
        location: ${{ secrets.PROD_GKE_ZONE }}

    - env:
        DEPLOYMENT: ${{ vars.DEPLOYMENT }}
        TAG: ghcr.io/${{ needs.release-to-uat.outputs.repo }}:${{ needs.release-to-uat.outputs.tag }}
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${TAG}
        kubectl rollout status deployment/${DEPLOYMENT}

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.release-to-uat.outputs.tag }}
        generateReleaseNotes: true
